### ISSUE TITLE
parsing fails on volumes using long syntax

### ISSUE THREAD

**Issue by runar-indico** [nautilusapp/nautilus#168]
If one is using the long [volume-syntax](https://docs.docker.com/compose/compose-file/#long-syntax-3), it will not be able to parse the file, like in the snippet below:

```yaml
      - type: bind
        source: ./nginx.conf.default
        target: /etc/nginx/nginx.conf
```

Currently, [the parser expects a string](https://github.com/oslabs-beta/nautilus/blob/8a6bbe5e320c5cc04bc8cbe4f82e44dc6aee2b18/src/renderer/helpers/yamlParser.ts#L28).

I added a PR in #167  to fix the issue.

---

This project looks interesting.
